
import { AppConfig, Language, WeatherModel, Location } from './types';

export const DEFAULT_LOCATIONS: Location[] = [
  { id: 'loc_1', name: 'Malmö', lat: 55.60498, lng: 13.00382 },
  { id: 'loc_2', name: 'Stockholm', lat: 59.3293, lng: 18.0686 },
  { id: 'loc_3', name: 'Göteborg', lat: 57.7089, lng: 11.9746 },
];

export const DEFAULT_CONFIG: AppConfig = {
  language: Language.SV,
  locations: DEFAULT_LOCATIONS,
  activeLocationId: 'loc_1',
  activeModels: [
    WeatherModel.SMHI,
    WeatherModel.YR,
    WeatherModel.DMI,
    WeatherModel.ECMWF
  ],
  geminiApiKey: ''
};

export const MODEL_COLORS: Record<WeatherModel, string> = {
  [WeatherModel.SMHI]: '#facc15', // Yellow-400
  [WeatherModel.YR]: '#38bdf8',   // Sky-400 (Yr Blue)
  [WeatherModel.DMI]: '#f87171',  // Red-400
  [WeatherModel.ECMWF]: '#60a5fa', // Blue-400
  [WeatherModel.ICON]: '#c084fc', // Purple-400
  [WeatherModel.GFS]: '#94a3b8',  // Slate-400
};

export const MODEL_LABELS: Record<WeatherModel, string> = {
  [WeatherModel.SMHI]: 'SMHI (SE)',
  [WeatherModel.YR]: 'Yr (NO)',
  [WeatherModel.DMI]: 'DMI (DK)',
  [WeatherModel.ECMWF]: 'ECMWF (EU)',
  [WeatherModel.ICON]: 'ICON (DE)',
  [WeatherModel.GFS]: 'GFS (US)',
};

export const TRANSLATIONS = {
  [Language.SV]: {
    settings: 'Inställningar',
    dashboard: 'Översikt',
    temperature: 'Temperatur',
    wind: 'Vind',
    windDirection: 'Vindriktning',
    humidity: 'Luftfuktighet',
    precipitation: 'Nederbörd',
    pressure: 'Lufttryck (hPa)',
    thunder: 'Åskrisk',
    clouds: 'Molnighet',
    aurora: 'Norrsken (Kp)',
    stargazer: 'Stjärnkikare',
    timeMachine: 'Tidsmaskin (-1 år)',
    aiAnalysis: 'AI Analys',
    exportConfig: 'Exportera Konfig (JSON)',
    importConfig: 'Importera Konfig (JSON)',
    save: 'Spara',
    cancel: 'Stäng',
    loading: 'Initierar WartemWeather...',
    error: 'Fel vid hämtning',
    addLocation: 'Lägg till plats',
    searchLocationPlaceholder: 'Sök stad eller adress...',
    search: 'Sök',
    models: 'Modeller',
    active: 'Aktiv',
    gusts: 'Byvind',
    low: 'Låg (0-2km)',
    mid: 'Mellan (2-7km)',
    high: 'Hög (>7km)',
    comparisonTemp: 'Jämförelse: Temperatur',
    comparisonWind: 'Jämförelse: Vindhastighet',
    comparisonRain: 'Jämförelse: Nederbörd',
    metrics: 'Mätvärden',
    metricsSubtitle: '(Senaste 24h)',
    now: 'Nu',
    frostWarning: 'FROSTVARNING: Risk för halka och känsliga växter.',
    coast: 'Kust & Hav',
    waves: 'Våghöjd',
    waveDir: 'Riktning',
    nature: 'Natur & Biologi',
    pollen: 'Pollenprognos',
    birch: 'Björk',
    grass: 'Gräs',
    mugwort: 'Gråbo',
    aqi: 'Luftkvalitet (AQI)',
    gardening: 'Trädgård (0cm)',
    soilTemp: 'Jordtemp (0cm)',
    rootTemp: 'Rottemp (18cm)',
    soilMoist: 'Fuktighet',
    sunCycle: 'Solcykel',
    sunrise: 'Upp',
    sunset: 'Ned',
    lifestyle: 'Livsstil & Hälsa',
    laundry: 'Torkväder',
    laundryGood: 'Utmärkt torkväder',
    laundryOk: 'Torkar långsamt',
    laundryBad: 'Häng ej ut tvätt',
    uvIndex: 'UV Index',
    elevation: 'm.ö.h',
    cape: 'Åska & Instabilitet',
    capeLabel: 'CAPE (J/kg)',
    stable: 'Stabil atmosfär',
    unstable: 'Måttligt instabil',
    veryUnstable: 'Kraftigt instabil',
    astro: 'Astro & Ljus',
    daylight: 'Dagsljus',
    moon: 'Månfas',
    newMoon: 'Nymåne',
    fullMoon: 'Fullmåne',
    visibility: 'Sikt & Flyg',
    fog: 'Dimma',
    haze: 'Dis/Dimmoln',
    goodVis: 'God sikt',
    clearVis: 'Klart',
    aviation: 'Flygregler (VFR)',
    language: 'Språk',
    apiKeyLabel: 'Gemini API Nyckel',
    apiKeyDesc: '(Valfritt) Endast för AI-analys. Väderdata fungerar utan denna.',
    dailyLimit: 'Daglig gräns nådd',
    usesLeft: 'kvar idag'
  },
  [Language.EN]: {
    settings: 'Settings',
    dashboard: 'Dashboard',
    temperature: 'Temperature',
    wind: 'Wind',
    windDirection: 'Wind Direction',
    humidity: 'Humidity',
    precipitation: 'Precipitation',
    pressure: 'Pressure (hPa)',
    thunder: 'Thunder Risk',
    clouds: 'Cloud Cover',
    aurora: 'Aurora (Kp)',
    stargazer: 'Stargazer Score',
    timeMachine: 'Time Machine (-1 yr)',
    aiAnalysis: 'AI Analysis',
    exportConfig: 'Export Config (JSON)',
    importConfig: 'Import Config (JSON)',
    save: 'Save',
    cancel: 'Close',
    loading: 'Initializing WartemWeather...',
    error: 'Error fetching data',
    addLocation: 'Add Location',
    searchLocationPlaceholder: 'Search city or address...',
    search: 'Search',
    models: 'Models',
    active: 'Active',
    gusts: 'Gusts',
    low: 'Low (0-2km)',
    mid: 'Mid (2-7km)',
    high: 'High (>7km)',
    comparisonTemp: 'Multi-Model Temperature',
    comparisonWind: 'Multi-Model Wind Speed',
    comparisonRain: 'Multi-Model Precipitation',
    metrics: 'Metrics',
    metricsSubtitle: '(Last 24h)',
    now: 'Now',
    frostWarning: 'FROST WARNING: Risk of ice and crop damage.',
    coast: 'Coast & Marine',
    waves: 'Wave Height',
    waveDir: 'Direction',
    nature: 'Nature & Biology',
    pollen: 'Pollen Forecast',
    birch: 'Birch',
    grass: 'Grass',
    mugwort: 'Mugwort',
    aqi: 'Air Quality (AQI)',
    gardening: 'Gardening (0cm)',
    soilTemp: 'Soil Temp (0cm)',
    rootTemp: 'Root Temp (18cm)',
    soilMoist: 'Moisture',
    sunCycle: 'Sun Cycle',
    sunrise: 'Rise',
    sunset: 'Set',
    lifestyle: 'Lifestyle & Health',
    laundry: 'Laundry Index',
    laundryGood: 'Dries Quickly',
    laundryOk: 'Dries Slowly',
    laundryBad: 'Don\'t Hang Out',
    uvIndex: 'UV Index',
    elevation: 'm.a.s.l.',
    cape: 'Thunder Potential',
    capeLabel: 'CAPE (J/kg)',
    stable: 'Stable Atmosphere',
    unstable: 'Moderately Unstable',
    veryUnstable: 'Highly Unstable',
    astro: 'Astro & Light',
    daylight: 'Daylight',
    moon: 'Moon Phase',
    newMoon: 'New Moon',
    fullMoon: 'Full Moon',
    visibility: 'Visibility & Aviation',
    fog: 'Fog',
    haze: 'Haze/Mist',
    goodVis: 'Good Visibility',
    clearVis: 'Clear',
    aviation: 'Flight Rules (VFR)',
    language: 'Language',
    apiKeyLabel: 'Gemini API Key',
    apiKeyDesc: '(Optional) Only for AI Analysis. Weather data works without this.',
    dailyLimit: 'Daily limit reached',
    usesLeft: 'left today'
  },
  [Language.DE]: {
    settings: 'Einstellungen',
    dashboard: 'Übersicht',
    temperature: 'Temperatur',
    wind: 'Wind',
    windDirection: 'Windrichtung',
    humidity: 'Luftfeuchtigkeit',
    precipitation: 'Niederschlag',
    pressure: 'Luftdruck (hPa)',
    thunder: 'Gewitterrisiko',
    clouds: 'Bewölkung',
    aurora: 'Polarlicht (Kp)',
    stargazer: 'Sternengucker',
    timeMachine: 'Zeitmaschine (-1 Jahr)',
    aiAnalysis: 'KI-Analyse',
    exportConfig: 'Konfig exportieren (JSON)',
    importConfig: 'Konfig importieren (JSON)',
    save: 'Speichern',
    cancel: 'Schließen',
    loading: 'Initialisiere WartemWeather...',
    error: 'Fehler beim Laden',
    addLocation: 'Ort hinzufügen',
    searchLocationPlaceholder: 'Stadt oder Adresse suchen...',
    search: 'Suchen',
    models: 'Modelle',
    active: 'Aktiv',
    gusts: 'Böen',
    low: 'Niedrig (0-2km)',
    mid: 'Mittel (2-7km)',
    high: 'Hoch (>7km)',
    comparisonTemp: 'Vergleich: Temperatur',
    comparisonWind: 'Vergleich: Wind',
    comparisonRain: 'Vergleich: Niederschlag',
    metrics: 'Messwerte',
    metricsSubtitle: '(Letzte 24h)',
    now: 'Jetzt',
    frostWarning: 'FROSTWARNUNG: Glättegefahr und Erntegefährdung.',
    coast: 'Küste & Meer',
    waves: 'Wellenhöhe',
    waveDir: 'Richtung',
    nature: 'Natur & Biologie',
    pollen: 'Pollenflug',
    birch: 'Birke',
    grass: 'Gräser',
    mugwort: 'Beifuß',
    aqi: 'Luftqualität (AQI)',
    gardening: 'Gartenbau (0cm)',
    soilTemp: 'Bodentemp (0cm)',
    rootTemp: 'Wurzeltemp (18cm)',
    soilMoist: 'Feuchtigkeit',
    sunCycle: 'Sonnenzyklus',
    sunrise: 'Aufgang',
    sunset: 'Untergang',
    lifestyle: 'Lifestyle & Gesundheit',
    laundry: 'Wäscheindex',
    laundryGood: 'Trocknet schnell',
    laundryOk: 'Trocknet langsam',
    laundryBad: 'Nicht raushängen',
    uvIndex: 'UV-Index',
    elevation: 'm ü. NHN',
    cape: 'Gewitterpotential',
    capeLabel: 'CAPE (J/kg)',
    stable: 'Stabile Atmosphäre',
    unstable: 'Mäßig instabil',
    veryUnstable: 'Stark instabil',
    astro: 'Astro & Licht',
    daylight: 'Tageslicht',
    moon: 'Mondphase',
    newMoon: 'Neumond',
    fullMoon: 'Vollmond',
    visibility: 'Sicht & Flug',
    fog: 'Nebel',
    haze: 'Dunst',
    goodVis: 'Gute Sicht',
    clearVis: 'Klar',
    aviation: 'Flugregeln (VFR)',
    language: 'Sprache',
    apiKeyLabel: 'Gemini API Key',
    apiKeyDesc: '(Optional) Nur für KI. Wetterdaten funktionieren ohne.',
    dailyLimit: 'Tageslimit erreicht',
    usesLeft: 'heute übrig'
  },
  [Language.FR]: {
    settings: 'Paramètres',
    dashboard: 'Tableau de bord',
    temperature: 'Température',
    wind: 'Vent',
    windDirection: 'Direction du vent',
    humidity: 'Humidité',
    precipitation: 'Précipitations',
    pressure: 'Pression (hPa)',
    thunder: 'Risque d\'orage',
    clouds: 'Nébulosité',
    aurora: 'Aurore (Kp)',
    stargazer: 'Observation des étoiles',
    timeMachine: 'Machine à voyager (-1 an)',
    aiAnalysis: 'Analyse IA',
    exportConfig: 'Exporter Config (JSON)',
    importConfig: 'Importer Config (JSON)',
    save: 'Enregistrer',
    cancel: 'Fermer',
    loading: 'Initialisation de WartemWeather...',
    error: 'Erreur de chargement',
    addLocation: 'Ajouter un lieu',
    searchLocationPlaceholder: 'Rechercher ville ou adresse...',
    search: 'Rechercher',
    models: 'Modèles',
    active: 'Actif',
    gusts: 'Rafales',
    low: 'Bas (0-2km)',
    mid: 'Moyen (2-7km)',
    high: 'Haut (>7km)',
    comparisonTemp: 'Comparaison: Température',
    comparisonWind: 'Comparaison: Vent',
    comparisonRain: 'Comparaison: Précipitations',
    metrics: 'Métriques',
    metricsSubtitle: '(Dernières 24h)',
    now: 'Maintenant',
    frostWarning: 'ALERTE GEL : Risque de verglas.',
    coast: 'Côte & Marine',
    waves: 'Hauteur des vagues',
    waveDir: 'Direction',
    nature: 'Nature & Biologie',
    pollen: 'Prévisions Pollen',
    birch: 'Bouleau',
    grass: 'Graminées',
    mugwort: 'Armoise',
    aqi: 'Qualité de l\'air (AQI)',
    gardening: 'Jardinage (0cm)',
    soilTemp: 'Temp. Sol (0cm)',
    rootTemp: 'Temp. Racine (18cm)',
    soilMoist: 'Humidité',
    sunCycle: 'Cycle Solaire',
    sunrise: 'Lever',
    sunset: 'Coucher',
    lifestyle: 'Style de vie & Santé',
    laundry: 'Indice Linge',
    laundryGood: 'Sèche vite',
    laundryOk: 'Sèche lentement',
    laundryBad: 'Ne pas étendre',
    uvIndex: 'Indice UV',
    elevation: 'alt.',
    cape: 'Potentiel Orageux',
    capeLabel: 'CAPE (J/kg)',
    stable: 'Atmosphère stable',
    unstable: 'Modérément instable',
    veryUnstable: 'Très instable',
    astro: 'Astro & Lumière',
    daylight: 'Lumière du jour',
    moon: 'Phase lunaire',
    newMoon: 'Nouvelle lune',
    fullMoon: 'Pleine lune',
    visibility: 'Visibilité & Aviation',
    fog: 'Brouillard',
    haze: 'Brume',
    goodVis: 'Bonne visibilité',
    clearVis: 'Clair',
    aviation: 'Règles de vol (VFR)',
    language: 'Langue',
    apiKeyLabel: 'Clé API Gemini',
    apiKeyDesc: '(Optionnel) Seulement pour l\'IA.',
    dailyLimit: 'Limite quotidienne atteinte',
    usesLeft: 'restants'
  },
  [Language.ES]: {
    settings: 'Configuración',
    dashboard: 'Panel',
    temperature: 'Temperatura',
    wind: 'Viento',
    windDirection: 'Dirección del viento',
    humidity: 'Humedad',
    precipitation: 'Precipitaciones',
    pressure: 'Presión (hPa)',
    thunder: 'Riesgo de Tormenta',
    clouds: 'Nubosidad',
    aurora: 'Aurora (Kp)',
    stargazer: 'Observación de estrellas',
    timeMachine: 'Máquina del tiempo (-1 año)',
    aiAnalysis: 'Análisis IA',
    exportConfig: 'Exportar Config (JSON)',
    importConfig: 'Importar Config (JSON)',
    save: 'Guardar',
    cancel: 'Cerrar',
    loading: 'Iniciando WartemWeather...',
    error: 'Error al cargar datos',
    addLocation: 'Añadir Ubicación',
    searchLocationPlaceholder: 'Buscar ciudad o dirección...',
    search: 'Buscar',
    models: 'Modelos',
    active: 'Activo',
    gusts: 'Ráfagas',
    low: 'Bajo (0-2km)',
    mid: 'Medio (2-7km)',
    high: 'Alto (>7km)',
    comparisonTemp: 'Comparación: Temperatura',
    comparisonWind: 'Comparación: Viento',
    comparisonRain: 'Comparación: Lluvia',
    metrics: 'Métricas',
    metricsSubtitle: '(Últimas 24h)',
    now: 'Ahora',
    frostWarning: 'ADVERTENCIA DE HELADA: Riesgo de hielo.',
    coast: 'Costa y Mar',
    waves: 'Altura de ola',
    waveDir: 'Dirección',
    nature: 'Naturaleza y Biología',
    pollen: 'Pronóstico de Polen',
    birch: 'Abedul',
    grass: 'Gramíneas',
    mugwort: 'Artemisa',
    aqi: 'Calidad del Aire (AQI)',
    gardening: 'Jardinería (0cm)',
    soilTemp: 'Temp. Suelo (0cm)',
    rootTemp: 'Temp. Raíz (18cm)',
    soilMoist: 'Humedad',
    sunCycle: 'Ciclo Solar',
    sunrise: 'Salida',
    sunset: 'Puesta',
    lifestyle: 'Estilo de Vida y Salud',
    laundry: 'Índice de Lavandería',
    laundryGood: 'Seca rápido',
    laundryOk: 'Seca lento',
    laundryBad: 'No tender',
    uvIndex: 'Índice UV',
    elevation: 'msnm',
    cape: 'Potencial de Tormenta',
    capeLabel: 'CAPE (J/kg)',
    stable: 'Atmósfera estable',
    unstable: 'Moderadamente inestable',
    veryUnstable: 'Muy inestable',
    astro: 'Astro y Luz',
    daylight: 'Luz diurna',
    moon: 'Fase lunar',
    newMoon: 'Luna nueva',
    fullMoon: 'Luna llena',
    visibility: 'Visibilidad y Aviación',
    fog: 'Niebla',
    haze: 'Neblina',
    goodVis: 'Buena visibilidad',
    clearVis: 'Claro',
    aviation: 'Reglas de vuelo (VFR)',
    language: 'Idioma',
    apiKeyLabel: 'Clave API Gemini',
    apiKeyDesc: '(Opcional) Solo para IA.',
    dailyLimit: 'Límite diario alcanzado',
    usesLeft: 'usos restantes'
  }
};
